# Generated by Django 5.0.6 on 2026-05-10 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight', models.TextField()),
                ('emotion_summary', models.JSONField(default=dict)),
                ('period', models.CharField(default='weekly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mood_insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.TextField()),
                ('detected_emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('fear', 'Fear'), ('anxiety', 'Anxiety'), ('calm', 'Calm'), ('love', 'Love'), ('excited', 'Excited'), ('stress', 'Stress'), ('motivation', 'Motivation'), ('depression', 'Depression'), ('surprise', 'Surprise'), ('disgust', 'Disgust'), ('neutral', 'Neutral')], max_length=50)),
                ('confidence_score', models.FloatField()),
                ('secondary_emotions', models.JSONField(default=list)),
                ('ai_response', models.TextField(blank=True, default='')),
                ('tips', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emotion_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='emotion_rec_user_id_c0057c_idx'), models.Index(fields=['detected_emotion'], name='emotion_rec_detecte_76b608_idx')],
            },
        ),
    ]
